# Generated by Django 5.0.7 on 2024-08-12 14:08

import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'Пользователья с таким ником уже существует.'}, max_length=30, unique=True, validators=[users.models.UserValidators.validate_username], verbose_name='Логин')),
                ('first_name', models.CharField(max_length=30, validators=[users.models.UserValidators.validate_names])),
                ('last_name', models.CharField(max_length=30, validators=[users.models.UserValidators.validate_names])),
                ('secret_word', models.CharField(max_length=64, validators=[users.models.UserValidators.validate_secret_word])),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('contacts', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reset_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
