# Generated by Django 5.0.7 on 2024-08-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_counter',
            field=models.IntegerField(default=0),
        ),
    ]
