# Generated by Django 5.0.7 on 2024-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_secret_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_word',
            field=models.CharField(max_length=64),
        ),
    ]
