# Generated by Django 5.0.7 on 2024-07-11 23:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username_userresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresettoken',
            name='expires',
        ),
        migrations.AddField(
            model_name='userresettoken',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 23, 45, 44, 96456, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userresettoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reset_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
