# Generated by Django 5.0.7 on 2024-07-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userresettoken_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresettoken',
            old_name='token',
            new_name='uuid',
        ),
    ]
