# Generated by Django 5.0.7 on 2024-07-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_token_userresettoken_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresettoken',
            name='session_key',
            field=models.CharField(default='eqwqweeqweqw', max_length=32),
            preserve_default=False,
        ),
    ]
