# Generated by Django 5.0.7 on 2024-07-13 17:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userresettoken_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[users.models.UserValidators.validate_names]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[users.models.UserValidators.validate_names]),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_word',
            field=models.CharField(max_length=64, validators=[users.models.UserValidators.validate_secret_word]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'Пользователья с таким ником уже существует.'}, max_length=30, unique=True, validators=[users.models.UserValidators.validate_username], verbose_name='Логин'),
        ),
    ]
