# Generated by Django 5.0.7 on 2024-07-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_unread_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unread_counter',
        ),
        migrations.AddField(
            model_name='user',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
