# Generated by Django 5.0.7 on 2024-07-13 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deferred', models.BooleanField(default=False)),
                ('deferred_datetime', models.DateTimeField(null=True)),
                ('answer_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.mail')),
                ('receiver', models.ManyToManyField(related_name='received_mails', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_mails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
