# Generated by Django 5.0.7 on 2024-07-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='receiver',
            new_name='receivers',
        ),
    ]
