# Generated by Django 5.0.7 on 2024-07-15 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_receiver_mail_receivers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='mail',
            name='answer_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.mail'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='deferred_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
