# Generated by Django 5.0.7 on 2024-08-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_mail_deferred_remove_mail_deferred_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delayedmail',
            name='answer_for',
        ),
    ]
