# Generated by Django 5.0.7 on 2024-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mail_options_alter_mail_answer_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='red',
            field=models.BooleanField(default=False),
        ),
    ]
