# Generated by Django 5.0.7 on 2024-08-10 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_delayedmail_answer_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='receivers',
        ),
        migrations.AddField(
            model_name='mail',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_mails', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
