# Generated by Django 5.0.7 on 2024-07-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mail_red'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='red',
            new_name='read',
        ),
    ]
