# Generated by Django 5.0.7 on 2024-08-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_delayedmail_receivers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftmail',
            name='receiver',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
