# Generated by Django 5.0.7 on 2024-07-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_draftmail_message_alter_draftmail_receivers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftmail',
            name='receivers',
        ),
        migrations.AddField(
            model_name='draftmail',
            name='receivers',
            field=models.TextField(blank=True),
        ),
    ]
